<style>
    td {
        padding-top: 0.5%;
        padding-bottom: 0.5%;
        text-align: center;
    }

    li {
        margin-bottom: .5%;
    }

    p,
    ol {
        text-align: justify;
    }

    .mytable {
        border-collapse: collapse;
        border: 1px solid #000;
    }

    .mytable>*>*>* {
        border: 1px solid #000;
    }

    img {
        width: 250px;
    }
</style>

<div>
    <h1 style="text-align: center; margin-bottom: 5%"><strong>Faculty/Employee</strong> Agreement</h1>
    <p>
        This <strong>Faculty/Employee</strong> Agreement (hereinafter “Agreement) is entered on this ______________ by and between, First
        Prize, Kota (Raj.) A private company incorporated under the provisions of the Companies Act, 2013 bearing CIN
        ____________________________ and having its registered office at No. _______ ______________________ India
        (hereinafter “First Prize”) and the <strong>Faculty/Employee</strong> (as defined on signature page). First Prize and Educator shall be
        individually referred to as “Party” and Collectively as “Parties”.</p>
    <div style="margin-top: 5%;">
        <table class="mytable">
            <tbody>
                <tr>
                    <td>1.</td>
                    <td>Service</td>
                    <td>
                        <p>As a <strong>Faculty/Employee</strong>, the <strong>Faculty/Employee</strong> will strive to add maximum lessons with topnotch content in any given category on www.eschoolindia.net (“Website”) and conduct live session on the First Prize platform (First Prize Platform) on mutually agreed topics.</p>
                    </td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Faculty</td>
                    <td>
                        Name :<br>
                        Pan :<br>
                        Address:
                    </td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td>Deliverables</td>
                    <td>
                        <p>During the terms of the Agreement the <strong>Faculty/Employee</strong> responsibility as a <strong>Faculty/Employee</strong> Shall be to</p>
                        <ol type="i" class="mt-2">
                            <li>
                                Create Courses on the Website
                            </li>
                            <li>
                                The Courses shall be in the language that is mutually agreed.
                            </li>
                            <li>Conducting special classes.</li>
                            <li>Update the KPL sheet that is shared via email on daily basis.</li>
                            <li>Maintain contact with the assigned First Prize point of contact (POC).</li>
                            <li>Promotion of Educator courses on social media or any other platform
                                unless a promotion plan is agreed with First Prize.</li>
                            <li>
                                Conduct Live Sessions on First Prize’s Platform.
                            </li>
                        </ol>
                        <p>The specific details of the monthly deliverables shall be mutually agreed and
                            confirmed on email and such email confirm shall be binding on both the Parties.</p>
                    </td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Payouts</td>
                    <td>
                        <p>The Educator shall receive the following payouts for the deliverables.</p>
                        <ol class="mt-2">
                            <li>
                                Payout as agreed and confirmed on email.
                            </li>
                            <li>
                                Additional incentives, if applicable, based on views milestones:
                            </li>
                        </ol>
                    </td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td>Account Monitoring</td>
                    <td>
                        <p>During the terms of this Agreement, the <strong>Faculty/Employee</strong>’s profile will be closely monitored on monthly basis. The monitoring shall be based on the date provided by First Prize’s internal algorithm which determines the quality of the lessons based on different parameters. A weekly review feedback shall be sent to the <strong>Faculty/Employee</strong> based on the data generated by the algorithm.</p>
                    </td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td>Event of Default</td>
                    <td>
                        <p>First Prize shall have the right in its sole discretion to suspend/terminate this Agreement and the <strong>Faculty/Employee</strong> status of the Educator if First Prize in its sole
                            opinion believes that the educator during the terms of the Agreement.</p>

                        <ol class="mt-2">
                            <li>
                                Has uploaded lessons which contain incorrect content or infringes any third
                                party copyrighted content.
                            </li>
                            <li>Has uploaded lesson that are of poor quality as per the data generated by
                                First Prize’s internal alogorithm.</li>
                            <li>Becomes unable to take any special Classes/Courses</li>
                            <li>Is not able to complete the mutually agreed deliverables within the agreed
                                timeline.</li>
                            <li>Is not consistent in his/her performance.</li>
                            <li>Is not disciplined in performing his/her deliverables.</li>
                            <li>Is involved in any activities that amount to misconduct</li>
                            <li>Has engaged in unethical methods to achieve his/her deliverables</li>
                            <li>Does not keep the terms of this Agreement confidential</li>
                            <li>Breached any terms of this agreement.</li>
                        </ol>
                    </td>
                </tr>
                <tr>
                    <td>7.</td>
                    <td>Delivery Timeline & License Period</td>
                    <td>
                        <ol>
                            <li>
                                <strong>Faculty/Employee</strong> will make sure that all his/her deliverables are performed
                                in timely manner and in accordance with the timelines that were agreed on email with the POC.
                            </li>
                            <li>
                                <strong>Faculty/Employee</strong> grants First Prize an exclusive license for a period of 2
                                years from the date of the live steam of Course or publication of any
                                <strong>Faculty/Employee</strong> Content of the <strong>Faculty/Employee</strong> on the Platform
                                during which period First Prize shall have the right to access, use, distribute
                                and publish the <strong>Faculty/Employee</strong> Content on its Platform & Website, as
                                the case maybe, for the access of its learners.
                            </li>
                        </ol>
                    </td>
                </tr>
                <tr>
                    <td>8.</td>
                    <td>Penalty</td>
                    <td>
                        <p>In case the <strong>Faculty/Employee</strong> fails to achieve the target then a penalty shall be applicable which shall be as communicated by email and at the sole discretion of First Prize. Further, payment shall be made on pro rata basis.</p>
                    </td>
                </tr>
                <tr>
                    <td>9.</td>
                    <td>Payment Terms</td>
                    <td>
                        <p>All eligible payouts shall be made in accordance with the timelines that are communicated to the <strong>Faculty/Employee</strong> by the POC over email. All eligible payouts shall be subject to applicable statutory deductions and applicable taxes.</p>
                    </td>
                </tr>
                <tr>
                    <td>10.</td>
                    <td>Term</td>
                    <td>
                        <p>This Agreement shall be effective from __________ to ______________ unless
                            terminated in accordance with the terms of this Agreement.</p>
                    </td>
                </tr>
                <tr>
                    <td>11.</td>
                    <td>Termination</td>
                    <td>
                        <ol type="a">
                            <li>
                                Termination at will: Either Party can terminate this Agreement by giving the
                                other Party a prior written notice of 10 days with or without providing any
                                reason for such termination.
                            </li>
                            <li>
                                Termination for Cause
                                <ol>
                                    <li>
                                        First Prize can terminate this Agreement in the Event of Default as
                                        mentioned in clause 6 by giving 7 days prior notice to the
                                        <strong>Faculty/Employee</strong>.
                                    </li>
                                    <li>
                                        First Prize may terminate this Agreement with immediate effect, if
                                        in the sole opinion of First Prize the Educator has breached the
                                        confidentiality obligation or is involved in any unethical practices
                                        or misconduct.
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </td>
                </tr>
                <tr>
                    <td>12.</td>
                    <td>Effect of Termination</td>
                    <td>
                        <p>Termination of the agreement shall not affect the payment liability of First Prize to the Educator for all the deliverables successfully performed by the Educator before the date of termination provided that such termination is not for misconduct or unethical practices, in such cases no payment shall be made to the <strong>Faculty/Employee</strong>.</p>
                    </td>
                </tr>
                <tr>
                    <td>13.</td>
                    <td>Confidentiality</td>
                    <td>
                        <p><strong>Faculty/Employee</strong> agrees and understands that this Agreement, it terms and any information relating to this Agreement are highly confidential and shall not be disclosed to any third party without the prior written approval of First Prize Notwithstanding anything contained in this Agreement, breach of this clause shall amount to immediate termination of this Agreement without any prior notice.</p>
                    </td>
                </tr>
                <tr>
                    <td>14.</td>
                    <td>Working Policies</td>
                    <td>
                        <ol type="i">
                            <li>The <strong>Faculty/Employee</strong> agrees and understands that the class can be arranged/taken from 6:00 am to 10 : 00 pm within this time duration per day.
                            </li>
                            <li>In full day <strong>Faculty/Employee</strong> can take six classes and two doubt classes in a day.</li>
                            <li><strong>Faculty/Employee</strong> can take maximum full day schedule as mention in sec 18 -> (ii) point and minimum one class and one doubt class in one day.</li>
                            <li>Company/Institute pay minimum Rs. 1,000/- per student per subject for complete session.</li>
                            <li>Company/Institute provide minimum 1,000 students in one session.</li>
                            <li>Company/Institute provide online platform for your extra income. So you cannot work with another platform other than First Prize for your personal benefit.</li>
                        </ol>
                    </td>
                </tr>
                <tr>
                    <td>15.</td>
                    <td>Content Ownership and removal</td>
                    <td>
                        <p>At all times <strong>Faculty/Employee</strong> retains ownership in the content created and provided for uploading on First Prize’s plus platform and Website, <strong>Faculty/Employee</strong> understand and agrees that First Prize incurs cost for providing the Website, conducting marketing and promotional activities. <strong>Faculty/Employee</strong> further agrees and understand that the consideration paid to <strong>Faculty/Employee</strong> under this Agreement is towards the license that <strong>Faculty/Employee</strong> gives First Prize to publish <strong>Faculty/Employee</strong> content. If during the terms of this Agreement or thereafter <strong>Faculty/Employee</strong> wishes to remove <strong>Faculty/Employee</strong> content from the Website, <strong>Faculty/Employee</strong> Agrees that First Prize shall have the right to recover and <strong>Faculty/Employee</strong> shall have the obligation to return to First Prize, and shall the amount that <strong>Faculty/Employee</strong> has received from First Prize during the term of this Agreement for the content uploaded on the Website including the milestone incentive payouts. For the purpose of clarity, content uploaded on the platform cannot be remove for the license period. <strong>Faculty/Employee</strong> understands and agree, however, that First Prize may retain, and may display, distribute, or perform, server copies of <strong>Faculty/Employee</strong> videos that have been removed or deleted.</p>
                    </td>
                </tr>
                <tr>
                    <td>16.</td>
                    <td>Online terms & condition and Privacy Policy</td>
                    <td>
                        <p>First Prize’s online terms and conditions and privacy policy that is available on <a href="<?php echo SITE_URL; ?>">www.firstprize.in</a> shall be applicable to the <strong>Faculty/Employee</strong> and shall become part of this Agreement by reference.</p>
                    </td>
                </tr>
                <tr>
                    <td>17.</td>
                    <td>Condition & Policies </td>
                    <td>
                        <p>These all Terms & Conditions for payment applicable full day equivalent. If Faculty/Employee work partially as compare to full one day working hours then the all payments divide partially in same ratio according with company policy. If you are satisfied then sign the agreement and start your work. Full day means Six full classes and two Doubt classes and duration of one class minimum 60 minutes and maximum 90 minutes. Then for partial work divide the payment in same ratio according to work duration of Faculty/Employee.</p>
                    </td>
                </tr>
                <tr>
                    <td>18.</td>
                    <td>Conflict</td>
                    <td>
                        <p>In case of any conflict between the provision of this Agreement and the online terms and conditions and privacy policy the terms of this Agreement shall prevail.</p>
                    </td>
                </tr>
                <tr>
                    <td>19.</td>
                    <td>Individual Contractors</td>
                    <td>
                        <p>The <strong>Faculty/Employee</strong> agrees and understands that nothing in this Agreement shall be construed to create an employment or agency relationship. Partnership or joint venture between First Prize and the <strong>Faculty/Employee</strong>. <strong>Faculty/Employee</strong> is an independent contractor and shall have no authority to bind or represent First Prize. <strong>Faculty/Employee</strong> shall not be entitled to participate in and/or receive any benefits that may be offered to First Prize’s employees from time to time. The <strong>Faculty/Employee</strong> acknowledges that First Prize has no obligation to withhold any income or other payroll taxes on the <strong>Faculty/Employee</strong>’s behalf other that as mentioned elsewhere under this Agreement and that the <strong>Faculty/Employee</strong> will be solely responsible for compliance with all state, central and local laws pertaining to statutory compliances, payment to its employees or withholding and payment of taxes upon the compensation provided for in this Agreement. <strong>Faculty/Employee</strong> shall indemnify, defend and hold harmless First Prize from and against any losses that First Prize incurs as a result of <strong>Faculty/Employee</strong>’s breach of its obligations under this Agreement or the online terms and condition and privacy policy available on <a href="<?php echo SITE_URL; ?>">www.firstprize.in</a>.</p>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <p>IN WITNESS WHEROR the Parties hereto have duly executed this Agreement as of the date and year hereinabove first written</p>
    <table align="center">
        <tr>
            <td style="width: 50%;">
                For, First Prize, Kota (Raj.)<br>
                _____________________________<br><br>
                <strong>Name: Psatis Patel/Rakesh Gupta</strong><br>
                <strong>Designation : Sr. Legal/Manager</strong><br>
            </td>
            <td style="width: 10%;">

            </td>
            <td style="width: 50%;">
                For, Faculty/Employee<br>
                _____________________________<br><br>
                <strong>Name : _____________________________</strong><br>
                <strong>Pan No. : ______________________________</strong><br>
            </td>
        </tr>
    </table>

</div>